### ISSUE TITLE
Production payments are not working

### ISSUE THREAD

**Issue by jalop123j** [open-pay/openpay-woocommerce#25]
In Sandbox mode the payments are working fine but in Production the payments are not approved. I am using Open pay cards v1.4.0

The site is orem.com.mx

![image](https://user-images.githubusercontent.com/30593787/44613093-0fd49080-a7dd-11e8-8d20-05a803d0cec8.png)

![image](https://user-images.githubusercontent.com/30593787/44613095-13681780-a7dd-11e8-9edb-d824098b59d3.png)

![image](https://user-images.githubusercontent.com/30593787/44613097-1bc05280-a7dd-11e8-9f9c-d7e7a24efb79.png)

![image](https://user-images.githubusercontent.com/30593787/44613098-1fec7000-a7dd-11e8-96b6-5dbf37ea8800.png)

![image](https://user-images.githubusercontent.com/30593787/44613114-45797980-a7dd-11e8-806e-7c5c93964fc1.png)

![image](https://user-images.githubusercontent.com/30593787/44613141-85406100-a7dd-11e8-8121-453527d73e3e.png)

**Comment by fedebalderas** [comment]
do you have the Openpay logs? can you copy the fail response from the logs and paste it here? i guess that the user "jalopXXXjXXXXX@gmail.com" was created in sandbox mode, so whe you try to complete a payment with this user in production mode it doesn't exists.

In your BD an ID from an Openpay client is related to your user, the pluign use this ID to complete transactions, so i'm sure that this ID is from an Openpay client in sandbox mode.

That's why you can complete transactions with one user and not the other one.

**Comment by jalop123j** [comment]
Hi fedebalderas,

To validate your assumption I did below steps:

- Create a new account 
- Perform a transaction in Sandbox environment (Succesfull)
- Change open pay plugin to production
- Do another transaction. I got exactly the same issue.

I can live with this issue as it should not impact customer payments, but I still think the plugin/server should handle this scenario as there is no message displayed back to the customer.
 
On a succesfull transaction I can see 2 entries: 201 Created / 200 OK.
In this scenario where the ID does not match, there is only 1 entry: 201 Created and then Plugin gets Internal error. Please see the first comment on this issue, I have attached print screens.

Please let me know if you need any aditional information.

Thanks for your help and perfect response.
